### PR TITLE
Add boolean 2D and 3D

### PR DESCRIPTION
**Pull request by EitanSomething**
I haven't tested this yet.
Modifiers will need to be modified

### CODE REVIEW

**Comment by eliemichel** [comment]
Once again @EitanSomething I don't want to break compatibility with OpenFX. This change modifies `ofxParam.h` which is part of the upstream API, as you can see here: https://github.com/ofxa/openfx/tree/master/include

So far there is only one difference, at it is well documented: https://github.com/eliemichel/OpenMeshEffect/blob/master/doc/guide/reference.md#key-differences-with-openfx This was decided because I really felt stuck when trying to get the location of the .ofx file, but as long as we can live without breaking OpenFX we should stick to it.

I am honestly sorry I have to reject some work you likely spent some time on, maybe try and ask first if it frustrates you. I tried to add a few issues in the bug tracker lately to make my train of though on this project clearer to new contributors like you, which I appreciate.

**Comment by EitanSomething** [comment]
I don't really see a problem breaking openfx api if it gives a better experience. Using opneFX as a base is a good start but it will need to be modified to better fit out purpose. I also think the file extension should be changed form ofx to ome to remove any confusion as to what file it is.

Is there a way to add this withour breaking the openFX api.

**Comment by eliemichel** [comment]
The point is, does this feature really give a better experience to anybody? If so, why didn't OpenFX implement it? Is there something in our case fundamentally different that makes bool vectors useful to us where they were not in OpenFX? If you come up with a real use case, no problem for breaking OpenFX, but I don't want to do it just out of speculation.

You can use any extension you like, the modifier will be able to load it. There is no real ambiguity in the sense that the ofx files contain by construction some metadata telling whether it implements either the Image Effect API or the Mesh Effect API, so Nuke/After Effect/Natron should gently reject an open mesh effect .ofx plugin.

**Comment by EitanSomething** [comment]
I guess boolean 2D and 3D aren't needed.

**Pull request closed without merging**
